# Generated by Django 6.1 on 2026-09-11 04:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeEditConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mặc định', max_length=100)),
                ('start_hour', models.IntegerField(default=8, help_text='Giờ bắt đầu (0-23)')),
                ('start_minute', models.IntegerField(default=0, help_text='Phút bắt đầu (0-59)')),
                ('end_hour', models.IntegerField(default=22, help_text='Giờ kết thúc (0-23)')),
                ('end_minute', models.IntegerField(default=0, help_text='Phút kết thúc (0-59)')),
                ('days_of_week', models.CharField(default='0,1,2,3,4,5,6', help_text='Ngày trong tuần cho phép (0=Thứ 2, 6=Chủ nhật)', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_management_gradeeditconfig',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('exam_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Đang diễn ra'), ('upcoming', 'Sắp tới'), ('completed', 'Đã kết thúc')], default='upcoming', max_length=20)),
                ('pre_exam_lock', models.BooleanField(default=False)),
                ('pre_exam_lock_date', models.DateField(blank=True, null=True)),
                ('pre_registration_lock', models.BooleanField(default=False)),
                ('pre_registration_lock_date', models.DateField(blank=True, null=True)),
                ('temporary_lock', models.BooleanField(default=False)),
                ('temporary_lock_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_management_semester',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fee_per_credit', models.IntegerField(default=500000)),
                ('increase_rate', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'student_management_university',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('session_token', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('session_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('session_device', models.TextField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='student_management_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='student_management_user_set', to='auth.permission')),
            ],
            options={
                'db_table': 'student_management_customuser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Đang học'), ('inactive', 'Nghỉ học'), ('graduated', 'Đã tốt nghiệp'), ('suspended', 'Đình chỉ')], default='active', max_length=50)),
                ('gpa', models.FloatField(default=0.0)),
                ('gpa10', models.FloatField(default=0.0)),
                ('tuition_debt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.university')),
            ],
            options={
                'db_table': 'student_management_student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Đang giảng dạy'), ('inactive', 'Nghỉ')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.university')),
            ],
            options={
                'db_table': 'student_management_teacher',
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('schedule', models.CharField(blank=True, default='', max_length=100)),
                ('room', models.CharField(blank=True, default='', max_length=50)),
                ('max_students', models.IntegerField(default=40)),
                ('credits', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management.semester')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management.teacher')),
            ],
            options={
                'db_table': 'student_management_courseclass',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Đã đăng ký'), ('cancelled', 'Đã huỷ'), ('completed', 'Hoàn thành')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.courseclass')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.student')),
            ],
            options={
                'db_table': 'student_management_registration',
                'unique_together': {('student', 'course_class')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.FloatField(blank=True, help_text='Chuyên cần (CC) — 20%', null=True)),
                ('midterm', models.FloatField(blank=True, help_text='Giữa kì (GK) — 30%', null=True)),
                ('final', models.FloatField(blank=True, help_text='Cuối kì (CK) — 50%', null=True)),
                ('average10', models.FloatField(blank=True, null=True)),
                ('average4', models.FloatField(blank=True, null=True)),
                ('letter_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('is_component_locked', models.BooleanField(default=False, help_text='Khoá điểm thành phần (CC, GK) — kích hoạt trước thi')),
                ('is_fully_locked', models.BooleanField(default=False, help_text='Khoá toàn bộ bảng điểm — kích hoạt trước ĐKHP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.courseclass')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.student')),
            ],
            options={
                'db_table': 'student_management_grade',
                'unique_together': {('student', 'course_class')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_number', models.IntegerField(default=1, help_text='Buổi học thứ mấy trong ngày (1, 2, ...)')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng mặt'), ('late', 'Đi trễ'), ('excused', 'Có phép')], default='present', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student_management.courseclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student_management.student')),
            ],
            options={
                'db_table': 'student_management_attendance',
                'ordering': ['-date', 'session_number'],
                'unique_together': {('student', 'course_class', 'date', 'session_number')},
            },
        ),
    ]
